name: .NET

on: [push, pull_request]

jobs:

  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: '8.0'

    - name: Build
      run: dotnet publish ./src/WindowsInk --configuration Release --framework net8.0 -o ./build/WindowsInk

    - uses: actions/upload-artifact@main
      with:
        name: WindowsInk
        path: |
          ./build/WindowsInk/*.dll
          !./build/WindowsInk/*.json
          !./build/WindowsInk/*.pdb
          !./build/WindowsInk/OpenTabletDriver.Plugin.dll
          !./build/WindowsInk/Newtonsoft.Json.dll
          !./build/WindowsInk/HidSharpCore.dll
